/*
 * JSP generated by Resin-3.2.0 (built Wed, 06 Aug 2008 08:41:33 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;

public class _adduser__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    response.setContentType("text/html");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
try{
String loginid=request.getParameter("userid");
String password1=request.getParameter("pass");
String name1=request.getParameter("name");
String email1=request.getParameter("email");
String dept1=request.getParameter("dept");
String extnumber=request.getParameter("exnumber");
String mnumber=request.getParameter("mobilenumber");
//############DATA BASE CONNECTIVITY#######################################################
		Class.forName("com.mysql.jdbc.Driver").newInstance();
		Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/roomdatabase","root","crs");
		Statement stmt=con.createStatement();
		ResultSet rs=null;
//##############################################################################################
		String presentID=null;
		presentID = (String)session.getAttribute("USERID");
String userstatus=null;
userstatus=request.getParameter("accessprivilage");
//################# QUERY TO CHECK WHETHER USERID OR EMAILID IS ALREADY EXISTED OR NOT ######################
rs=stmt.executeQuery("select * from user where (loginID='"+loginid+"' or email='"+email1+"')");
//#################CHWCKING INPUT VALUES IF ANY ONE IS NULL OR NOT ######################################
if(loginid==null || password1==null || name1==null || email1==null ||dept1==null || extnumber==null || mnumber== null || userstatus==null)
	{
			
    out.write(_jsp_string1, 0, _jsp_string1.length);
    }
else
	{
if(!rs.next())
	{
	int i=0;
	//########################## UPDATING TABLE#########################################################
i=stmt.executeUpdate("insert into user(loginID,password,name,email,department,extenNumber,mobileNumber,IDStatus,accessPrivilage,lastUpdatedUser) values('"+loginid+"','"+password1+"','"+name1+"','"+email1+"','"+dept1+"','"+extnumber+"','"+mnumber+"','ACTIVE','"+userstatus+"','"+presentID+"')");
stmt.close();
con.close();
if(i>0)
		{
		
    out.write(_jsp_string2, 0, _jsp_string2.length);
    
		}
		else
		{
			
    out.write(_jsp_string3, 0, _jsp_string3.length);
    
		}
	}
else
	{
	
    out.write(_jsp_string4, 0, _jsp_string4.length);
    }
	}
}
catch(Exception e)
{
//out.println(e.toString());

    out.write(_jsp_string5, 0, _jsp_string5.length);
    
}

    out.write(_jsp_string6, 0, _jsp_string6.length);
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1541868491438029340L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("adduser.jsp"), 9147623633224737337L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      super.init(config);
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string1;
  private final static char []_jsp_string6;
  private final static char []_jsp_string5;
  private final static char []_jsp_string0;
  private final static char []_jsp_string4;
  private final static char []_jsp_string2;
  private final static char []_jsp_string3;
  static {
    _jsp_string1 = "<font size=4 face=\"Baskerville Old Face\" color=red>Sorry No field is null. Please Enter valid data in each and every feild</font><br>\r\n			<font size=4 face=\"Baskerville Old Face\" color=red>Access Privilage Should be selected</font>\r\n	".toCharArray();
    _jsp_string6 = "\r\n</body>\r\n</html>".toCharArray();
    _jsp_string5 = "<font size=4 face=\"Baskerville Old Face\" color=red>Please Check the input data again.Each and every field should not exceed maximum and length and should not be Null. (OR) ENABLE JAVASCRIPT OPTION IN YOUR BROWSER. For other details contact Administrator</font><br>".toCharArray();
    _jsp_string0 = "\r\n\r\n<html>\r\n<head>  <TITLE>  ROOM ALLOCATION SYSTEM - ADDING USER</TITLE>\r\n</head>\r\n<body background=\"abc.jpg\" >\r\n".toCharArray();
    _jsp_string4 = "<font size=4 face=\"Baskerville Old Face\" color=red>Sorry LoginID or Email is already existed. Try again by choosing different userid or emailid</font>\r\n	".toCharArray();
    _jsp_string2 = "	<br>\r\n<font size=4 face=\"Baskerville Old Face\" color=green> \r\nUser details are successfully added to database\r\n</font>".toCharArray();
    _jsp_string3 = "<font size=4 face=\"Baskerville Old Face\" color=red>Sorry User Details are not added to Database. Please Check the input values and try again or Contact Administrator</font><br>".toCharArray();
  }
}
