/*
 * JSP generated by Resin-3.2.0 (built Wed, 06 Aug 2008 08:41:33 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class _checkIndividualReportsFinal__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    response.setContentType("text/html");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
try{
		Class.forName("com.mysql.jdbc.Driver").newInstance();
		Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/roomdatabase","root","crs");
		Statement stmt=con.createStatement();
		Statement stmt1=con.createStatement();
		String cc=null;cc=(String)session.getAttribute("USERID");//out.println(cc);
		if(cc==null)
	 {
			
    out.write(_jsp_string1, 0, _jsp_string1.length);
    
	 }
		ResultSet rs=null,rs2=null;
		String roomid=null,syear=null,smonth=null,sdate=null;
		String eyear=null,edate=null,emonth=null;
		String startdate=null,enddate=null,nextstartdate=null;
		String roomno=null;
		String str=request.getParameter("submitQuery");
		if(str.equals("submit"))
	{
		int syear1=0,smonth1=0,sdate1=0,eyear1=0,emonth1=0,edate1=0;
		roomid=request.getParameter("roomno");
		if(!roomid.equals("roomno"))
		{
			if(!roomid.equals("ALL"))
			{
			//out.println(roomid);
			rs2=stmt.executeQuery("select * from room where roomID='"+roomid+"'");
			rs2.next();
			roomno=rs2.getString(2);
			rs2.close();
			////// FOR TODAY DATE/////////////
			Calendar cal = Calendar.getInstance();
        int day100 = cal.get(Calendar.DATE);
        int month100 = cal.get(Calendar.MONTH) + 1;
        int year100 = cal.get(Calendar.YEAR);
		int day200=31;
		int month200=12;
		int year200=year100+40;
		//////////////////////////////////////////
		syear=""+year100;syear1=Integer.parseInt(syear);
		smonth=""+month100;smonth1=Integer.parseInt(smonth);smonth1=smonth1-1;
		sdate=""+day100;sdate1=Integer.parseInt(sdate);
		eyear=""+year200;eyear1=Integer.parseInt(eyear);
		emonth=""+month200;emonth1=Integer.parseInt(emonth);emonth1=emonth1-1;
		edate=""+day200;edate1=Integer.parseInt(edate);
		startdate=syear+"-"+smonth+"-"+sdate;
		int tempvar=smonth1+2;
		nextstartdate=syear+"-"+tempvar+"-"+sdate;
		String currentmonth=syear+"-"+smonth+"-"+1;
		enddate=eyear+"-"+emonth+"-"+edate;
		Calendar c1 = Calendar.getInstance();
		Calendar c2 = Calendar.getInstance();
		Calendar c111 = Calendar.getInstance();
		Calendar c222 = Calendar.getInstance();
		c111.set(syear1,smonth1,sdate1);
		c222.set(eyear1,emonth1,edate1);
		String monthstring=null;
		switch(smonth1)
			{
			case 0: monthstring="JANUARY";break;
			case 1: monthstring="FEBRUARY";break;
			case 2: monthstring="MARCH";break;
			case 3: monthstring="APRIL";break;
			case 4: monthstring="MAY";break;
			case 5: monthstring="JUNE";break;
			case 6: monthstring="JULY";break;
			case 7: monthstring="AUGUST";break;
			case 8: monthstring="SEPTEMBER";break;
			case 9: monthstring="OCTOBER";break;
			case 10: monthstring="NOVEMBER";break;
			case 11: monthstring="DECEMBER";break;
			}
			if(c111.before(c222))
		{
		c1.set(syear1,smonth1,1);
		c2.set(eyear1,emonth1,1);
		String passingString=null;
		passingString=roomid+"_"+startdate+"_"+enddate+"_"+startdate+"_"+"NEXT";
	//	out.println(passingString);
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((roomno));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.println(monthstring);out.println("-"+syear1);
    out.write(_jsp_string4, 0, _jsp_string4.length);
    if(c1.before(c2))
		{
			
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((passingString));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    }
    out.write(_jsp_string7, 0, _jsp_string7.length);
    int x=c1.get(Calendar.DAY_OF_WEEK);
		//out.println(x);
		int daysInMonth = c1.getActualMaximum(Calendar.DAY_OF_MONTH);
		String DATE_FORMAT = "yyyy-MM-dd";
		java.text.SimpleDateFormat simpledataformat = new java.text.SimpleDateFormat(DATE_FORMAT);
		//out.println(simpledataformat.format(c1.getTime()).toString());
        int month = c1.get(Calendar.MONTH) + 1;
        int year = c1.get(Calendar.YEAR);
		String firstdate=year+"-"+month+"-"+1;
		String lastdate=year+"-"+month+"-"+31;
		rs=stmt.executeQuery("select * from roomallocation,requestroom where roomallocation.requestID=requestroom.requestID and givenDate>='"+firstdate+"' and givenDate<='"+lastdate+"' and roomallocation.roomID='"+roomid+"' and allocationstatus='NOTCOMPLETED'");
		if(rs.next())
		{
			rs.previous();
			Hashtable tablerow=new Hashtable();
			int i=0;
			String gdate=null;
			String gstime=null;
			String getime=null;
			String gtitle=null;
			String totalstring=null;
			while(rs.next())
			{
				gdate=rs.getString(4);
				String gg=rs.getString(5);
				String gg1[]=gg.split(":");
				gstime=gg1[0]+":"+gg1[1];
				gg=rs.getString(6);
				String gg2[]=gg.split(":");
				getime=gg2[0]+":"+gg2[1];
				gtitle=rs.getString(19);
				totalstring=gdate+"_"+gstime+"_"+getime+"_"+gtitle;
				tablerow.put(totalstring,new Integer(i));
				i++;
			}
			int initialloop=8-x;
			int date=1;
		
				for(int j=1;j<x;j++)
				{
					
    out.write(_jsp_string8, 0, _jsp_string8.length);
    }
					for(int k=1;k<=initialloop;k++)
					{
						Enumeration e = tablerow.keys();
						String tempstr=null;
						String findstime=null;
						String findetime=null;
						String findtitle=null;
						int found=0;
						String date10=null;
						while( e. hasMoreElements() ){
						 tempstr=(String)e.nextElement();
						String tempstr2[]=tempstr.split("_");
						date10=tempstr2[0];
						findstime=tempstr2[1];
						findetime=tempstr2[2];
						findtitle=tempstr2[3];
						String date100[]=date10.split("-");
						int actdate=Integer.parseInt(date100[2]);
						if(actdate==date){
							found=1;
							break;
						}
						}
						if(found==1)
						{
							
								
    out.write(_jsp_string9, 0, _jsp_string9.length);
    
									String strToNextPage=null;
								strToNextPage=roomid+"&"+date10+"&"+roomid+"_"+startdate+"_"+enddate+"_"+nextstartdate+"_"+"PREVIOUS";
								
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((strToNextPage));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    	out.println(date);
    out.write(_jsp_string12, 0, _jsp_string12.length);
    //out.println("   "+findtitle);out.println(findstime);out.println("-"+findetime);
    out.write(_jsp_string13, 0, _jsp_string13.length);
    date++;
						}
						else
						{						
					
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((date));
    out.write(_jsp_string15, 0, _jsp_string15.length);
     date++;
						}
					}
					
    out.write(_jsp_string16, 0, _jsp_string16.length);
    for(int i1=0;date<=daysInMonth;i1++)
				{
    out.write(_jsp_string17, 0, _jsp_string17.length);
    
				for(int p=1;p<=7;p++)
					{
						if(date<=daysInMonth){
				Enumeration e = tablerow.keys();
						String tempstr=null;
						String findstime=null;
						String findetime=null;
						String findtitle=null;
						int found=0;
						String date10=null;
						while( e. hasMoreElements() ){
						 tempstr=(String)e.nextElement();
						String tempstr2[]=tempstr.split("_");
						date10=tempstr2[0];
						findstime=tempstr2[1];
						findetime=tempstr2[2];
						findtitle=tempstr2[3];
						String date100[]=date10.split("-");
						int actdate=Integer.parseInt(date100[2]);
						if(actdate==date){
							found=1;
							break;
						}
						}
						if(found==1)
						{
								
    out.write(_jsp_string9, 0, _jsp_string9.length);
    
								String strToNextPage=null;
								strToNextPage=roomid+"&"+date10+"&"+roomid+"_"+startdate+"_"+enddate+"_"+nextstartdate+"_"+"PREVIOUS";
								
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((strToNextPage));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    out.println(date);
    out.write(_jsp_string12, 0, _jsp_string12.length);
    //out.println("   "+findtitle);out.println(findstime);out.println("-"+findetime);
    out.write(_jsp_string13, 0, _jsp_string13.length);
    date++;
						
						}
						else
						{						
					
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((date));
    out.write(_jsp_string15, 0, _jsp_string15.length);
     date++;
						}
				}
					}
    out.write(_jsp_string18, 0, _jsp_string18.length);
    }
			
		}
		else
		{		
		int initialloop=8-x;
		int date=1;
		
				for(int j=1;j<x;j++)
				{
					
    out.write(_jsp_string8, 0, _jsp_string8.length);
    }
					for(int k=1;k<=initialloop;k++)
					{
					
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((date));
    out.write(_jsp_string15, 0, _jsp_string15.length);
     date++;}
					
    out.write(_jsp_string16, 0, _jsp_string16.length);
    for(int i=0;date<=daysInMonth;i++)
				{
    out.write(_jsp_string17, 0, _jsp_string17.length);
    
				for(int p=1;p<=7;p++)
					{
						if(date<=daysInMonth){
    out.write(_jsp_string19, 0, _jsp_string19.length);
    out.print((date));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    date++;}
					}
    out.write(_jsp_string18, 0, _jsp_string18.length);
    }
		}
		
    out.write(_jsp_string21, 0, _jsp_string21.length);
    
	}
	else
		{
			
    out.write(_jsp_string22, 0, _jsp_string22.length);
    }
				}
		else
		{
//###########################################################


			//out.println("code for ALL");


		////// FOR TODAY DATE/////////////
			Calendar cal = Calendar.getInstance();
        int day100 = cal.get(Calendar.DATE);
        int month100 = cal.get(Calendar.MONTH) + 1;
        int year100 = cal.get(Calendar.YEAR);
		int day200=31;
		int month200=12;
		int year200=year100+10;
		//////////////////////////////////////////
		syear=""+year100;syear1=Integer.parseInt(syear);
		smonth=""+month100;smonth1=Integer.parseInt(smonth);smonth1=smonth1-1;
		sdate=""+day100;sdate1=Integer.parseInt(sdate);
		eyear=""+year200;eyear1=Integer.parseInt(eyear);
		emonth=""+month200;emonth1=Integer.parseInt(emonth);emonth1=emonth1-1;
		edate=""+day200;edate1=Integer.parseInt(edate);
		startdate=syear+"-"+smonth+"-"+sdate;
		int tempvar=smonth1+2;
		nextstartdate=syear+"-"+tempvar+"-"+sdate;
		startdate=syear+"-"+smonth+"-"+sdate;
		String currentmonth=syear+"-"+smonth+"-"+1;
		enddate=eyear+"-"+emonth+"-"+edate;
		Calendar c1 = Calendar.getInstance();
		Calendar c2 = Calendar.getInstance();
		Calendar c111 = Calendar.getInstance();
		Calendar c222 = Calendar.getInstance();
		c111.set(syear1,smonth1,sdate1);
		c222.set(eyear1,emonth1,edate1);
		String monthstring=null;
		switch(smonth1)
			{
			case 0: monthstring="JANUARY";break;
			case 1: monthstring="FEBRUARY";break;
			case 2: monthstring="MARCH";break;
			case 3: monthstring="APRIL";break;
			case 4: monthstring="MAY";break;
			case 5: monthstring="JUNE";break;
			case 6: monthstring="JULY";break;
			case 7: monthstring="AUGUST";break;
			case 8: monthstring="SEPTEMBER";break;
			case 9: monthstring="OCTOBER";break;
			case 10: monthstring="NOVEMBER";break;
			case 11: monthstring="DECEMBER";break;
			}
			if(c111.before(c222))
		{
		c1.set(syear1,smonth1,1);
		c2.set(eyear1,emonth1,1);
		String passingString=null;
		passingString=roomid+"_"+startdate+"_"+enddate+"_"+startdate+"_"+"NEXT";
	//	out.println(passingString);
    out.write(_jsp_string23, 0, _jsp_string23.length);
    out.print((startdate));
    out.write(_jsp_string24, 0, _jsp_string24.length);
    out.print((enddate));
    out.write(_jsp_string25, 0, _jsp_string25.length);
    out.println(monthstring);out.println("-"+syear1);
    out.write(_jsp_string26, 0, _jsp_string26.length);
    if(c1.before(c2))
		{
			
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((passingString));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    }
    out.write(_jsp_string7, 0, _jsp_string7.length);
    int x=c1.get(Calendar.DAY_OF_WEEK);
		//out.println(x);
		int daysInMonth = c1.getActualMaximum(Calendar.DAY_OF_MONTH);
		String DATE_FORMAT = "yyyy-MM-dd";
		java.text.SimpleDateFormat simpledataformat = new java.text.SimpleDateFormat(DATE_FORMAT);
		//out.println(simpledataformat.format(c1.getTime()).toString());
        int month = c1.get(Calendar.MONTH) + 1;
        int year = c1.get(Calendar.YEAR);
		String firstdate=year+"-"+month+"-"+1;
		String lastdate=year+"-"+month+"-"+31;
		rs=stmt.executeQuery("select * from roomallocation,requestroom where roomallocation.requestID=requestroom.requestID and givenDate>='"+firstdate+"' and givenDate<='"+lastdate+"' and allocationstatus='NOTCOMPLETED'");
		if(rs.next())
		{
			rs.previous();
			Hashtable tablerow=new Hashtable();
			int i=0;
			String gdate=null;
			String gstime=null;
			String getime=null;
			String gtitle=null;
			String totalstring=null;
			while(rs.next())
			{
				gdate=rs.getString(4);
				String gg=rs.getString(5);
				String gg1[]=gg.split(":");
				gstime=gg1[0]+":"+gg1[1];
				gg=rs.getString(6);
				String gg2[]=gg.split(":");
				getime=gg2[0]+":"+gg2[1];
				gtitle=rs.getString(19);
				totalstring=gdate+"_"+gstime+"_"+getime+"_"+gtitle;
				tablerow.put(totalstring,new Integer(i));
				i++;
			}
			int initialloop=8-x;
			int date=1;
		
				for(int j=1;j<x;j++)
				{
					
    out.write(_jsp_string8, 0, _jsp_string8.length);
    }
					for(int k=1;k<=initialloop;k++)
					{
						Enumeration e = tablerow.keys();
						String tempstr=null;
						String findstime=null;
						String findetime=null;
						String findtitle=null;
						int found=0;
						String date10=null;
						while( e. hasMoreElements() ){
						 tempstr=(String)e.nextElement();
						String tempstr2[]=tempstr.split("_");
						date10=tempstr2[0];
						findstime=tempstr2[1];
						findetime=tempstr2[2];
						findtitle=tempstr2[3];
						String date100[]=date10.split("-");
						int actdate=Integer.parseInt(date100[2]);
						if(actdate==date){
							found=1;
							break;
						}
						}
						if(found==1)
						{
							
								
    out.write(_jsp_string9, 0, _jsp_string9.length);
    
									String strToNextPage=null;
								strToNextPage=roomid+"&"+date10+"&"+roomid+"_"+startdate+"_"+enddate+"_"+nextstartdate+"_"+"PREVIOUS";
								
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((strToNextPage));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    	out.println(date);
    out.write(_jsp_string12, 0, _jsp_string12.length);
    //out.println("   "+findtitle);out.println(findstime);out.println("-"+findetime);
    out.write(_jsp_string13, 0, _jsp_string13.length);
    date++;
						}
						else
						{						
					
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((date));
    out.write(_jsp_string15, 0, _jsp_string15.length);
     date++;
						}
					}
					
    out.write(_jsp_string16, 0, _jsp_string16.length);
    for(int i1=0;date<=daysInMonth;i1++)
				{
    out.write(_jsp_string17, 0, _jsp_string17.length);
    
				for(int p=1;p<=7;p++)
					{
						if(date<=daysInMonth){
				Enumeration e = tablerow.keys();
						String tempstr=null;
						String findstime=null;
						String findetime=null;
						String findtitle=null;
						int found=0;
						String date10=null;
						while( e. hasMoreElements() ){
						 tempstr=(String)e.nextElement();
						String tempstr2[]=tempstr.split("_");
						date10=tempstr2[0];
						findstime=tempstr2[1];
						findetime=tempstr2[2];
						findtitle=tempstr2[3];
						String date100[]=date10.split("-");
						int actdate=Integer.parseInt(date100[2]);
						if(actdate==date){
							found=1;
							break;
						}
						}
						if(found==1)
						{
								
    out.write(_jsp_string9, 0, _jsp_string9.length);
    
								String strToNextPage=null;
								strToNextPage=roomid+"&"+date10+"&"+roomid+"_"+startdate+"_"+enddate+"_"+nextstartdate+"_"+"PREVIOUS";
								
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((strToNextPage));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    out.println(date);
    out.write(_jsp_string12, 0, _jsp_string12.length);
    //out.println("   "+findtitle);out.println(findstime);out.println("-"+findetime);
    out.write(_jsp_string13, 0, _jsp_string13.length);
    date++;
						
						}
						else
						{						
					
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((date));
    out.write(_jsp_string15, 0, _jsp_string15.length);
     date++;
						}
				}
					}
    out.write(_jsp_string18, 0, _jsp_string18.length);
    }
			
		}
		else
		{		
		int initialloop=8-x;
		int date=1;
		
				for(int j=1;j<x;j++)
				{
					
    out.write(_jsp_string8, 0, _jsp_string8.length);
    }
					for(int k=1;k<=initialloop;k++)
					{
					
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((date));
    out.write(_jsp_string15, 0, _jsp_string15.length);
     date++;}
					
    out.write(_jsp_string16, 0, _jsp_string16.length);
    for(int i=0;date<=daysInMonth;i++)
				{
    out.write(_jsp_string17, 0, _jsp_string17.length);
    
				for(int p=1;p<=7;p++)
					{
						if(date<=daysInMonth){
    out.write(_jsp_string19, 0, _jsp_string19.length);
    out.print((date));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    date++;}
					}
    out.write(_jsp_string18, 0, _jsp_string18.length);
    }
		}
		
    out.write(_jsp_string27, 0, _jsp_string27.length);
    
	}
	else
		{
			
    out.write(_jsp_string22, 0, _jsp_string22.length);
    }


//###############################################################
		}
		}
		else
		{
			
    out.write(_jsp_string28, 0, _jsp_string28.length);
    }
	
	}
	else
	{
		//out.println("code for another operations");
	}
	
}
catch(Exception e)
{
	//out.println(e.toString());
	
    out.write(_jsp_string29, 0, _jsp_string29.length);
    
}
    out.write(_jsp_string30, 0, _jsp_string30.length);
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1541868491438029340L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("checkIndividualReportsFinal.jsp"), -4999464745118369258L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      super.init(config);
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string4;
  private final static char []_jsp_string19;
  private final static char []_jsp_string2;
  private final static char []_jsp_string11;
  private final static char []_jsp_string15;
  private final static char []_jsp_string20;
  private final static char []_jsp_string10;
  private final static char []_jsp_string9;
  private final static char []_jsp_string17;
  private final static char []_jsp_string16;
  private final static char []_jsp_string13;
  private final static char []_jsp_string0;
  private final static char []_jsp_string23;
  private final static char []_jsp_string12;
  private final static char []_jsp_string30;
  private final static char []_jsp_string29;
  private final static char []_jsp_string27;
  private final static char []_jsp_string26;
  private final static char []_jsp_string28;
  private final static char []_jsp_string8;
  private final static char []_jsp_string21;
  private final static char []_jsp_string24;
  private final static char []_jsp_string5;
  private final static char []_jsp_string3;
  private final static char []_jsp_string22;
  private final static char []_jsp_string7;
  private final static char []_jsp_string25;
  private final static char []_jsp_string1;
  private final static char []_jsp_string14;
  private final static char []_jsp_string18;
  private final static char []_jsp_string6;
  static {
    _jsp_string4 = "</font>\r\n		<hr>\r\n		</center>\r\n		".toCharArray();
    _jsp_string19 = "\r\n				<td bgcolor=green align=\"center\">".toCharArray();
    _jsp_string2 = "\r\n	<div align=\"left\"><font size=5 face=\"TimesNewRoman\" color=darkpink><b><I>Room details for a particular month</I></b></font></div>\r\n		\r\n		<center><font size=5 face=\"TimesNewRoman\" color=blue>Room number</font>&nbsp;&nbsp;&nbsp;<font size=5 face=\"TimesNewRoman\" color=green>".toCharArray();
    _jsp_string11 = "\">".toCharArray();
    _jsp_string15 = "</td>\r\n					".toCharArray();
    _jsp_string20 = "</td>\r\n				".toCharArray();
    _jsp_string10 = "<a href=\"dateReport.jsp?".toCharArray();
    _jsp_string9 = "<td bgcolor=red align=\"center\">".toCharArray();
    _jsp_string17 = "\r\n				<tr>".toCharArray();
    _jsp_string16 = "</tr>\r\n				".toCharArray();
    _jsp_string13 = "</td>\r\n								".toCharArray();
    _jsp_string0 = "<html>\r\n \r\n\r\n\r\n\r\n<head>  <TITLE>  ROOM ALLOCATION SYSTEM </TITLE></head>\r\n<body background=abc.jpg>\r\n".toCharArray();
    _jsp_string23 = "\r\n		<center>\r\n		<table><tr><td><font size=5 face=\"TimesNewRoman\" color=blue>Start Date</font></td><td><font size=4 face=\"TimesNewRoman\" color=green>".toCharArray();
    _jsp_string12 = "</a><br>".toCharArray();
    _jsp_string30 = "\r\n\r\n</body>\r\n</html>".toCharArray();
    _jsp_string29 = "<center>\r\n<br><font size=5 face=\"TimesNewRoman\" color=RED> PLEASE	SELECT THE INPUTS CORRECTLY..AND TRY AGAIN</font>\r\n".toCharArray();
    _jsp_string27 = "</table><br>\r\n		<div align=right><I><B><font size=5 face=\"TimesNewRoman\" color=RED>RED</font></b></i>--<font size=4 face=\"TimesNewRoman\" color=RED>Represents Partially Available</font><br>\r\n<I><B><font size=5 face=\"TimesNewRoman\" color=GREEN>GREEN</font></b></i>--<font size=4 face=\"TimesNewRoman\" color=GREEN>Represents Fully Available</font><br></div>\r\n		<script>\r\ndocument.write(\"<input type='button' \" +\r\n\"onClick='window.print()' \" +\r\n\"class='printbutton' \" +\r\n\"value='Print This Page'/>\");\r\n</script>".toCharArray();
    _jsp_string26 = "</font>\r\n		</center>\r\n		".toCharArray();
    _jsp_string28 = "<center>\r\n<br><font size=5 face=\"TimesNewRoman\" color=RED> PLEASE	SELECT THE INPUTS (ROOMID) CORRECTLY..AND TRY AGAIN</font>\r\n		".toCharArray();
    _jsp_string8 = "<td></td>\r\n				".toCharArray();
    _jsp_string21 = "</table><br>\r\n	<div align=right>	<I><B><font size=5 face=\"TimesNewRoman\" color=RED>RED</font></b></i>--<font size=4 face=\"TimesNewRoman\" color=RED>Represents Partially Available</font><br>\r\n<I><B><font size=5 face=\"TimesNewRoman\" color=GREEN>GREEN</font></b></i>--<font size=4 face=\"TimesNewRoman\" color=GREEN>Represents Fully Available</font><br></div>\r\n		<script>\r\ndocument.write(\"<input type='button' \" +\r\n\"onClick='window.print()' \" +\r\n\"class='printbutton' \" +\r\n\"value='Print This Page'/>\");\r\n</script>\r\n".toCharArray();
    _jsp_string24 = "</font></td><td></td><td></td><td><font size=5 face=\"TimesNewRoman\" color=blue>End Date</font></td><td><font size=4 face=\"TimesNewRoman\" color=green>".toCharArray();
    _jsp_string5 = "<div align=\"right\"><a href=\"nextcheckIndividualReports.jsp?".toCharArray();
    _jsp_string3 = "</font>&nbsp;&nbsp;&nbsp;\r\n		<font size=5 face=\"TimesNewRoman\" color=blue>Current month</font>&nbsp;&nbsp;&nbsp;<font size=4 face=\"TimesNewRoman\" color=green>".toCharArray();
    _jsp_string22 = "<center>\r\n<br><font size=5 face=\"TimesNewRoman\" color=RED> PLEASE	SELECT THE INPUTS (DATES ORDER) CORRECTLY..AND TRY AGAIN</font>\r\n".toCharArray();
    _jsp_string7 = "\r\n		<center>\r\n<table cellspacing=2 cellpadding=2 border=1 width=400 height=200>\r\n<tr><td align=\"center\"><font size=4 face=\"TimesNewRoman\" color=blue>SUN</font></td><td align=\"center\"><font size=4 face=\"TimesNewRoman\" color=blue>MON</font></td><td align=\"center\"><font size=4 face=\"TimesNewRoman\" color=blue>TUE</font></td><td align=\"center\"><font size=4 face=\"TimesNewRoman\" color=blue>WED</font></td><td align=\"center\"><font size=4 face=\"TimesNewRoman\" color=blue>THU</font></td><td align=\"center\"><font size=4 face=\"TimesNewRoman\" color=blue>FRI</font></td><td align=\"center\"><font size=4 face=\"TimesNewRoman\" color=blue>SAT</font></td></tr><tr align=\"center\">\r\n		".toCharArray();
    _jsp_string25 = "</font></td></tr>\r\n		</table>\r\n		<center><font size=5 face=\"TimesNewRoman\" color=blue>RoomID</font>&nbsp;&nbsp;&nbsp;<font size=5 face=\"TimesNewRoman\" color=green>ALLROOMS</font>\r\n		<font size=5 face=\"TimesNewRoman\" color=blue>Current Month</font>&nbsp;&nbsp;&nbsp;<font size=4 face=\"TimesNewRoman\" color=green>".toCharArray();
    _jsp_string1 = "<div align=right><font size=4 face=\"TimesNewRoman\" color=blue><a href=\"MainPage.html\" target=\"_top\">Home</a></font>".toCharArray();
    _jsp_string14 = "<td bgcolor=green align=\"center\">".toCharArray();
    _jsp_string18 = "\r\n					</tr>		\r\n					".toCharArray();
    _jsp_string6 = "\">NEXT MONTH</a></div>\r\n		".toCharArray();
  }
}
