/*
 * JSP generated by Resin-3.2.0 (built Wed, 06 Aug 2008 08:41:33 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class _dateReport__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    response.setContentType("text/html");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
try{
	Class.forName("com.mysql.jdbc.Driver").newInstance();
		Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/roomdatabase","root","crs");
		Statement stmt=con.createStatement();
		Statement stmt1=con.createStatement();
		ResultSet rs=null,rs2=null;
String getstr=request.getQueryString();
//out.println("sdsds------"+getstr);
String divarray[]=getstr.split("&");
String curdate=null;
String roomid=null;
roomid=divarray[0];
if(!roomid.equals("ALL"))
	{
curdate=divarray[1];
String sp[]=curdate.split("-");
int year1=Integer.parseInt(sp[0]);
int month1=Integer.parseInt(sp[1]);
int date1=Integer.parseInt(sp[2]);
Calendar c1 = Calendar.getInstance();
c1.set(year1,(month1-1),date1);
int x=c1.get(Calendar.DAY_OF_WEEK);
//out.println(x);
String passstr=divarray[2];
rs=stmt.executeQuery("select roomno from room where roomID='"+roomid+"'");
String roomnumber=null;
rs.next();
roomnumber=rs.getString(1);
rs.close();
//out.println("to next page---"+passstr);

    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((passstr));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    
String dayofweek=null;
switch(x)
	{
	case 1:dayofweek="SUNDAY";break;
	case 2:dayofweek="MONDAY";break;
	case 3:dayofweek="TUESDAY";break;
	case 4:dayofweek="WEDNESDAY";break;
	case 5:dayofweek="THURSDAY";break;
	case 6:dayofweek="FRIDAY";break;
	case 7:dayofweek="SATURDAY";break;
	}
//	out.println(dayofweek);
rs=stmt.executeQuery("select * from roomallocation,requestroom,user where roomallocation.requestID=requestroom.requestID and requestroom.userID=user.userID and roomID='"+divarray[0]+"' and givenDate='"+divarray[1]+"' order by roomallocation.startTime,roomallocation.endTime");

    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((roomnumber));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((curdate));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((dayofweek));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    
while(rs.next())
	{
		String stime=rs.getString(5);
		String tempstime[]=stime.split(":");
		String realstime=tempstime[0]+":"+tempstime[1];
		String etime=rs.getString(6);
		String tempetime[]=etime.split(":");
		String realetime=tempetime[0]+":"+tempetime[1];
		String title=rs.getString(19);
		
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.println(realstime+"-"+realetime);
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((title));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((rs.getString(31)));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    
	}
		
    out.write(_jsp_string11, 0, _jsp_string11.length);
    
	}
else
	{
//#########################################################################################################
//	out.println("code for all rooms");
	curdate=divarray[1];
String sp[]=curdate.split("-");
int year1=Integer.parseInt(sp[0]);
int month1=Integer.parseInt(sp[1]);
int date1=Integer.parseInt(sp[2]);
Calendar c1 = Calendar.getInstance();
c1.set(year1,(month1-1),date1);
int x=c1.get(Calendar.DAY_OF_WEEK);
//out.println(x);
String passstr=divarray[2];
//out.println("div string  "+divarray[2]);
//rs=stmt.executeQuery("select roomno from room where roomID='"+roomid+"'");
String roomnumber=null;
//rs.next();
//roomnumber=rs.getString(1);
//rs.close();
//out.println("to next page---"+passstr);

    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((passstr));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    
String dayofweek=null;
switch(x)
	{
	case 1:dayofweek="SUNDAY";break;
	case 2:dayofweek="MONDAY";break;
	case 3:dayofweek="TUESDAY";break;
	case 4:dayofweek="WEDNESDAY";break;
	case 5:dayofweek="THURSDAY";break;
	case 6:dayofweek="FRIDAY";break;
	case 7:dayofweek="SATURDAY";break;
	}
//	out.println(dayofweek);
rs=stmt.executeQuery("select * from roomallocation,requestroom,room where roomallocation.requestID=requestroom.requestID and roomallocation.roomID=room.roomID and givenDate='"+divarray[1]+"' order by roomallocation.startTime,roomallocation.endTime");

    out.write(_jsp_string13, 0, _jsp_string13.length);
    out.print((curdate));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((dayofweek));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    
while(rs.next())
	{
		String stime=rs.getString(5);
		String tempstime[]=stime.split(":");
		String realstime=tempstime[0]+":"+tempstime[1];
		String etime=rs.getString(6);
		String tempetime[]=etime.split(":");
		String realetime=tempetime[0]+":"+tempetime[1];
		String title=rs.getString(19);
		
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.println(realstime+"-"+realetime);
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((title));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((rs.getString(29)));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    
	}
		
    out.write(_jsp_string11, 0, _jsp_string11.length);
    

//#########################################################################################################
	}
}
catch(Exception e)
{
	//out.println(e.toString());
	
    out.write(_jsp_string16, 0, _jsp_string16.length);
    
}
    out.write(_jsp_string17, 0, _jsp_string17.length);
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1541868491438029340L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("dateReport.jsp"), -3275957227538985008L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      super.init(config);
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string17;
  private final static char []_jsp_string14;
  private final static char []_jsp_string1;
  private final static char []_jsp_string15;
  private final static char []_jsp_string8;
  private final static char []_jsp_string4;
  private final static char []_jsp_string6;
  private final static char []_jsp_string13;
  private final static char []_jsp_string16;
  private final static char []_jsp_string7;
  private final static char []_jsp_string11;
  private final static char []_jsp_string5;
  private final static char []_jsp_string9;
  private final static char []_jsp_string0;
  private final static char []_jsp_string10;
  private final static char []_jsp_string12;
  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  static {
    _jsp_string17 = "\r\n</body>\r\n</html>".toCharArray();
    _jsp_string14 = "</font></td><td></td><td><font size=4 face=\"TimesNewRoman\" color=blue>DAY_OF_THE_WEEK</font></td><td><font size=4 face=\"TimesNewRoman\" color=darkbrown>".toCharArray();
    _jsp_string1 = "\r\n<font size=5 face=\"TimesNewRoman\" color=darkpink><I><B>Room details for a particular day</B></I></font>\r\n<div align=\"right\"><a href=\"nextcheckIndividualReports.jsp?".toCharArray();
    _jsp_string15 = "</font></td></tr></table>\r\n<table border=1 cellspacing=3 cellpadding=3><tr><td align=center><font size=4 face=\"TimesNewRoman\" color=blue>Timings</font></td><td></td><td align=center><font size=4 face=\"TimesNewRoman\" color=blue>TITLE</font></td><td><font size=4 face=\"TimesNewRoman\" color=blue>Allocated Room</font></td></tr>\r\n".toCharArray();
    _jsp_string8 = "</font></td><td></td><td><font size=4 face=\"TimesNewRoman\" color=green>".toCharArray();
    _jsp_string4 = "</font></td><td>&nbsp;&nbsp;&nbsp;</td><td><font size=4 face=\"TimesNewRoman\" color=blue>Date</font></td><td><font size=4 face=\"TimesNewRoman\" color=darkbrown>".toCharArray();
    _jsp_string6 = "</font></td></tr></table><br>\r\n<table border=1><tr><td align=center><font size=4 face=\"TimesNewRoman\" color=blue>TIMINGS</font></td><td></td><td align=center><font size=4 face=\"TimesNewRoman\" color=blue>TITLE</font></td><td align=center><font size=4 face=\"TimesNewRoman\" color=blue>REQUESTED BY</font></td></tr>\r\n".toCharArray();
    _jsp_string13 = "\r\n<div align=\"left\"><font size=5 face=\"TimesNewRoman\" color=darkpink>All Rooms Details for a Particular Day</font></div><br>\r\n<table border=0>\r\n<tr><td></td><td><font size=4 face=\"TimesNewRoman\" color=darkpink>FOR ALLROOMS</font></td><td></td><td><font size=4 face=\"TimesNewRoman\" color=blue>DATE</font></td><td><font size=4 face=\"TimesNewRoman\" color=darkbrown>".toCharArray();
    _jsp_string16 = "<font size=4 face=\"Baskerville Old Face\" color=red>Sorry problem with database. TRY AGAIN. For other details contact Administrator</font><br>".toCharArray();
    _jsp_string7 = "<tr><td><font size=4 face=\"TimesNewRoman\" color=green>".toCharArray();
    _jsp_string11 = "</table>\r\n		<script>\r\ndocument.write(\"<input type='button' \" +\r\n\"onClick='window.print()' \" +\r\n\"class='printbutton' \" +\r\n\"value='Print This Page'/>\");\r\n</script>\r\n		".toCharArray();
    _jsp_string5 = "</font></td><td>&nbsp;&nbsp;&nbsp;</td><td><font size=4 face=\"TimesNewRoman\" color=blue>Day_of_the_week</font></td><td><font size=4 face=\"TimesNewRoman\" color=darkbrown>".toCharArray();
    _jsp_string9 = "</font></td><td><font size=4 face=\"TimesNewRoman\" color=green>".toCharArray();
    _jsp_string0 = "<html>\r\n<head>  <TITLE>  ROOM ALLOCATION SYSTEM </TITLE></head>\r\n \r\n\r\n\r\n\r\n<body background=abc.jpg>\r\n".toCharArray();
    _jsp_string10 = "</font></td></tr>".toCharArray();
    _jsp_string12 = "\r\n<div align=\"right\"><a href=\"nextcheckIndividualReports.jsp?".toCharArray();
    _jsp_string3 = "\r\n<table border=0>\r\n<tr><td><font size=4 face=\"TimesNewRoman\" color=blue>Room number</font></td><td><font size=4 face=\"TimesNewRoman\" color=darkbrown>".toCharArray();
    _jsp_string2 = "\">BACK</a></div>\r\n<center>\r\n".toCharArray();
  }
}
