/*
 * JSP generated by Resin-3.2.0 (built Wed, 06 Aug 2008 08:41:33 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.io.*;

public class _MyindividualRequest__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    response.setContentType("text/html");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
 String requestID=request.getQueryString();
 String requeststatus=null;
 requeststatus=request.getParameter("requeststatus");
 //out.println(requeststatus+" "+requestID);
 try{
		 Class.forName("com.mysql.jdbc.Driver").newInstance();
		Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/roomdatabase","root","crs");
		Statement stmt=con.createStatement();
		if(requeststatus==null)
	 {
		ResultSet rs=null;
		String status=null;
		rs=stmt.executeQuery("select * from requestroom,user,locationtable where (requestroom.userID=user.userID and locationtable.locationId=requestroom.location and requestID='"+requestID+"') order by requestID asc");
		rs.next();

		
    out.write(_jsp_string1, 0, _jsp_string1.length);
     session.setAttribute("REQUESTID",rs.getString(1));session.setMaxInactiveInterval(36000);
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((rs.getString(20)));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((rs.getString(3)));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((rs.getString(4)));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((rs.getString(5)));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((rs.getString(6)));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((rs.getString(32)));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((rs.getString(8)));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((rs.getString(10)));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    status=rs.getString(15);
    out.write(_jsp_string11, 0, _jsp_string11.length);
    out.print((status));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((rs.getString(11)));
    out.write(_jsp_string13, 0, _jsp_string13.length);
    out.print((rs.getString(9)));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((rs.getString(18)));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    rs.close();
if(status.equals("APPROVED"))
		 {
	rs=stmt.executeQuery("select distinct(roomno) from roomallocation,room where roomallocation.roomID=room.roomID and roomallocation.requestID='"+requestID+"'");
	if(rs.next())
			 {
    out.write(_jsp_string16, 0, _jsp_string16.length);
    out.print((rs.getString(1)));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    
			 }
		 }

    out.write(_jsp_string17, 0, _jsp_string17.length);
    }
 else{}
}
catch(Exception e)
{
	//out.println(e.toString());
	
    out.write(_jsp_string18, 0, _jsp_string18.length);
    

}


 
    out.write(_jsp_string19, 0, _jsp_string19.length);
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1541868491438029340L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("MyindividualRequest.jsp"), 4099778760295458850L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      super.init(config);
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string6;
  private final static char []_jsp_string17;
  private final static char []_jsp_string16;
  private final static char []_jsp_string11;
  private final static char []_jsp_string10;
  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  private final static char []_jsp_string14;
  private final static char []_jsp_string19;
  private final static char []_jsp_string7;
  private final static char []_jsp_string18;
  private final static char []_jsp_string12;
  private final static char []_jsp_string0;
  private final static char []_jsp_string8;
  private final static char []_jsp_string9;
  private final static char []_jsp_string3;
  private final static char []_jsp_string5;
  private final static char []_jsp_string13;
  private final static char []_jsp_string4;
  private final static char []_jsp_string15;
  static {
    _jsp_string6 = "</font></td><td><font size=4 face=\"Baskerville Old Face\" color=blue>End Time</font></td><td><font size=4 face=\"Baskerville Old Face\" color=green>".toCharArray();
    _jsp_string17 = "\r\n</table>\r\n<script>\r\ndocument.write(\"<input type='button' \" +\r\n\"onClick='window.print()' \" +\r\n\"class='printbutton' \" +\r\n\"value='Print This Page'/>\");\r\n</script>\r\n".toCharArray();
    _jsp_string16 = "\r\n<tr><td><font size=4 face=\"Baskerville Old Face\" color=blue>Allocated Room</font></td><td colspan=4><font size=4 face=\"Baskerville Old Face\" color=green>".toCharArray();
    _jsp_string11 = "\r\n<td><font size=4 face=\"Baskerville Old Face\" color=blue>Status</td><td><font size=5 face=\"Baskerville Old Face\" color=green>".toCharArray();
    _jsp_string10 = "</font></td>\r\n".toCharArray();
    _jsp_string1 = "\r\n		<form method=\"post\" action=\"individualRequest.jsp\">\r\n <center>\r\n".toCharArray();
    _jsp_string2 = "\r\n<table border=0>\r\n<tr><td></td><td><font size=4 face=\"Baskerville Old Face\" color=blue>Requested User</font></td><td><font size=4 face=\"Baskerville Old Face\" color=green>".toCharArray();
    _jsp_string14 = "</font></td></tr>\r\n<tr><td><font size=4 face=\"Baskerville Old Face\" color=blue>Approval Comments</font></td><td colspan=4><font size=4 face=\"Baskerville Old Face\" color=green>".toCharArray();
    _jsp_string19 = "\r\n </body>\r\n </html>".toCharArray();
    _jsp_string7 = "</font></td></tr>\r\n\r\n<tr><td><font size=4 face=\"Baskerville Old Face\" color=blue>Location</td><td><font size=4 face=\"Baskerville Old Face\" color=green>".toCharArray();
    _jsp_string18 = "<font size=4 face=\"Baskerville Old Face\" color=red>Sorry Problem with the database. TRY AGAIN AFTER SOME TIME. For other details contact Administrator</font><br>".toCharArray();
    _jsp_string12 = "</td>\r\n</tr>\r\n<tr><td><font size=4 face=\"Baskerville Old Face\" color=blue>Request Type</font></td><td colspan=4><font size=4 face=\"Baskerville Old Face\" color=green>".toCharArray();
    _jsp_string0 = " \r\n\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n<HTML>\r\n <HEAD>\r\n   <TITLE>  ROOM ALLOCATION SYSTEM </TITLE>\r\n  <META NAME=\"Generator\" CONTENT=\"EditPlus\">\r\n  <META NAME=\"Author\" CONTENT=\"\">\r\n  <META NAME=\"Keywords\" CONTENT=\"\">\r\n  <META NAME=\"Description\" CONTENT=\"\">\r\n </HEAD>\r\n\r\n <BODY background=abc.jpg>\r\n\r\n ".toCharArray();
    _jsp_string8 = "</font></td><td><font size=4 face=\"Baskerville Old Face\" color=blue>Capacity</font></td><td><font size=4 face=\"Baskerville Old Face\" color=green>".toCharArray();
    _jsp_string9 = "</font></td></tr>\r\n\r\n<tr><td><font size=4 face=\"Baskerville Old Face\" color=blue>Recurring Title</td><td><font size=4 face=\"Baskerville Old Face\" color=green>".toCharArray();
    _jsp_string3 = "</font></td><td></td></tr><tr></tr>\r\n\r\n<tr><td><font size=4 face=\"Baskerville Old Face\" color=blue>Start Date</td><td><font size=4 face=\"Baskerville Old Face\" color=green>".toCharArray();
    _jsp_string5 = "</font></td></tr>\r\n\r\n<tr><td><font size=4 face=\"Baskerville Old Face\" color=blue>Start Time</td><td><font size=4 face=\"Baskerville Old Face\" color=green>".toCharArray();
    _jsp_string13 = "</font></td></tr>\r\n<tr><td><font size=4 face=\"Baskerville Old Face\" color=blue>Purpose</font></td><td colspan=4><font size=4 face=\"Baskerville Old Face\" color=green>".toCharArray();
    _jsp_string4 = "</font></td><td><font size=4 face=\"Baskerville Old Face\" color=blue>End Date</font></td><td><font size=4 face=\"Baskerville Old Face\" color=green>".toCharArray();
    _jsp_string15 = "</font></td></tr>\r\n".toCharArray();
  }
}
